Update games.json
AreWeAntiCheatYet/AreWeAntiCheatYet pull request #1734
Opened 2024-10-03 01:44 UTC by StellaLovesTech

Epic has removed BattlEye from Fortnite

Does not change its status, it still is Denied.

(proof, there is no longer a battleye folder or the battleye exe)
![image](https://github.com/user-attachments/assets/37775113-1ecb-4b79-b9ae-f7bf3c6c9663)
![image](https://github.com/user-attachments/assets/4196c6cd-f65f-40aa-9d0d-91ff81108030)
![image](https://github.com/user-attachments/assets/9e6eb42a-6c3a-4185-82c1-7f126fdb9a8a)

2024-10-04 06:32 UTC, Starz0r requested changes
Could you also edit the `date_changed` field? Doesn't have to be accurate, but it does need to be changed since some tools using the manifest rely on this field.

2024-10-04 15:42 UTC, StellaLovesTech commented
> Could you also edit the `date_changed` field? Doesn't have to be accurate, but it does need to be changed since some tools using the manifest rely on this field.

Done

2024-10-04 18:08 UTC, StellaLovesTech commented
> Could you also edit the `date_changed` field? Doesn't have to be accurate, but it does need to be changed since some tools using the manifest rely on this field.

alr done

2024-10-05 15:47 UTC, Starz0r approved these changes

2024-10-05 15:48 UTC, merged